language: node_js
sudo: required
branches:
  only:
    - master
    - develop
    - /^issue.*$/
node_js:
  - '4'
  - '6'
  - '8'
os:
  - linux
  - osx
dist: trusty
osx_image: xcode8
before_install:
    - if [[ $TRAVIS_NODE_VERSION == "8" ]]; then npm install -g npm@4; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get head; fi
    - git clone https://github.com/IBM-Swift/Package-Builder.git
script:
  - osName="linux"
  # Overwrite if OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then osName="osx"; fi
  - export projectFolder=`pwd`
  - projectName="$(basename $projectFolder)"
  - export SWIFT_SNAPSHOT=swift-3.1.1
  - source ./Package-Builder/install-swift.sh
  - npm run coverage
  - npm run report-coverage

jobs:
  include:
  - stage: Review
    node_js: '6'
    script: "./review.sh"
  - stage: Releases
    language: ruby
    script: "./release.sh"
env:
  global:
    - CXX=g++-4.8
