language: node_js
sudo: required
branches:
  only:
    - master
    - develop
node_js:
  - '4'
  - '6'
os:
  - linux
  - osx
dist: trusty
osx_image: xcode8
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get head; fi
    - git clone https://github.com/IBM-Swift/Package-Builder.git
script:
  - osName="linux"
  # Overwrite if OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then osName="osx"; fi
  - export projectFolder=`pwd`
  - projectName="$(basename $projectFolder)"
  - export SWIFT_SNAPSHOT=swift-3.1.1
  - source ./Package-Builder/install-swift.sh
  - npm run coverage
  - npm run report-coverage

env:
  global:
    - CXX=g++-4.8
