language: node_js
sudo: required
branches: 
  only:
    - master
node_js:
  - '4'
  - '6'
os:
  - linux
  - osx
dist: trusty
osx_image: xcode8
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get head; fi   
    - git clone https://github.com/rob-deans/Package-Builder.git
script:
  - source ./Package-Builder/install-swift.sh `pwd` 
  - npm test && npm run testint

env:
  global:
    - CXX=g++-4.8

