language: node_js
branches: 
  only:
    - master
matrix:
  include:
   - os: linux
     dist: trusty
     sudo: required
     node_js: '4'
   - os: linux
     dist: trusty
     sudo: required
     node_js: '6'
   - os: osx
     osx_image: xcode8.1
     sudo: required
     node_js: '4'
   - os: osx
     osx_image: xcode8.1
     sudo: required
     node_js: '6'
before_install:
    - git clone https://github.com/IBM-Swift/Package-Builder.git
script:
  - ./Package-Builder/install-swift.sh `pwd` 
  - npm test && npm run testint

env:
  global:
    - CXX=g++-4.8

